/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package test.com;

import java.io.IOException;
import java.io.PrintWriter;
import java.sql.*;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;

/**
 *
 * @author Ruchir
 */
@WebServlet(name = "sendmail", urlPatterns = {"/sendmail"})
public class sendmail extends HttpServlet {

    /** 
     * Processes requests for both HTTP <code>GET</code> and <code>POST</code> methods.
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    protected void processRequest(HttpServletRequest request, HttpServletResponse response)
            throws Exception {
        response.setContentType("text/html;charset=UTF-8");
        PrintWriter out = response.getWriter();
        String email=request.getParameter("email");
        String cname=request.getParameter("name");
        String cid=request.getParameter("compid");
        String msg=request.getParameter("message");
        try {
            /* TODO output your page here
            out.println("<html>");
            out.println("<head>");
            out.println("<title>Servlet sendmail</title>");  
            out.println("</head>");
            out.println("<body>");
            out.println("<h1>Servlet sendmail at " + request.getContextPath () + "</h1>");
            out.println("</body>");
            out.println("</html>");
             */
            Connection con=null;
            Statement stmt2=null;
            
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mnrega", "root", "prady");
            stmt2 = con.createStatement();
            String command1="Select * from complain where compid='"+cid+"'";
            ResultSet rst = stmt2.executeQuery(command1);
            boolean flag=true;
            if(rst.next())
            {
                if(rst.getString("cstatus").equals("Solved"))
                {
                    out.println("The Complain is already Solved!!!");
                    out.println("Click");
                    out.println("<a href='compheader.jsp'>Here </a>'");
                    out.println("to Continue");
                    flag=false;
                }
            }
            if(flag)
            {
            
            String command = "UPDATE complain SET cstatus='Solved'WHERE compid='"+cid+"'";
            int i= stmt2.executeUpdate(command);
            
            if(i==1)
            {
            // Emailing    
                final String username = "mnrega.apr@gmail.com";
		final String password = "ashu.pradyu.cr";
 
		Properties props = new Properties();
		props.put("mail.smtp.auth", "true");
		props.put("mail.smtp.starttls.enable", "true");
		props.put("mail.smtp.host", "smtp.gmail.com");
		props.put("mail.smtp.port", "587");
 
		Session session = Session.getInstance(props,
		  new javax.mail.Authenticator() {
            @Override
			protected PasswordAuthentication getPasswordAuthentication() {
				return new PasswordAuthentication(username, password);
			}
		  });
 
		try {
 
			Message message = new MimeMessage(session);
			message.setFrom(new InternetAddress("mnrega.apr@gmail.com"));
			message.setRecipients(Message.RecipientType.TO,
				InternetAddress.parse(email));
			message.setSubject("Complain Solved");
			message.setText("Hello,"+cname
				+ "\n\n Your Complain has been Solved."
                                +"Your Complain ID is:  "+cid
                                +"\n\n"+msg
                                +".\n\nThank You."
                                + "\n\nThis is an autogenerated Email.Kindly do not reply");
 
			Transport.send(message);
 
			//System.out.println("Email Done");
 
		} 
                catch (MessagingException e) {
                    out.println("Exception in sending email"+e.getLocalizedMessage());
			throw new RuntimeException(e);
        }}
            out.println("The Email has been Sent");
            out.println("Click");
                    out.println("<a href='managerhome.jsp'>Here </a>'");
                    out.println("to Continue");
            }}catch(Exception e)
            {out.println("Exception in sendmail"+e.getLocalizedMessage());}
        finally {            
            out.close();
        }
    }

    // <editor-fold defaultstate="collapsed" desc="HttpServlet methods. Click on the + sign on the left to edit the code.">
    /** 
     * Handles the HTTP <code>GET</code> method.
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        try {
            processRequest(request, response);
        } catch (Exception ex) {
            Logger.getLogger(sendmail.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /** 
     * Handles the HTTP <code>POST</code> method.
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        try {
            processRequest(request, response);
        } catch (Exception ex) {
            Logger.getLogger(sendmail.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /** 
     * Returns a short description of the servlet.
     * @return a String containing servlet description
     */
    @Override
    public String getServletInfo() {
        return "Short description";
    }// </editor-fold>
}
